### ISSUE TITLE
Unusual links and state of Data Elements when previewed

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper-NHSD/mdm-plugin-nhs-data-dictionary#83]
# Overview

NHSE have reported an unusual state for a Data Element (though it may affect others). The issue is quite long winded, so please follow these instructions below.

# Steps to replicate

First, view the current live version of the Data Element "ACCOMMODATION TYPE END DATE" at https://www.datadictionary.nhs.uk/data_elements/accommodation_type_end_date.html. Note that:

1. Is has a text line saying "ACCOMMODATION TYPE END DATE is the same as attribute PERSON PROPERTY EFFECTIVE END DATE."
2. It has one linked attribute called "PERSON PROPERTY EFFECTIVE END DATE"

![image](https://github.com/user-attachments/assets/1623dbbf-1fe5-487a-9ac9-870a4570a07d)

Now look for this Data Element in the Orchestrator preview under the "Test branch" on the test system, and note:

1. The "is the same as" text is missing
2. There is a linked attribute to "ACCOMMODATION TYPE END DATE"

![image](https://github.com/user-attachments/assets/f7f07fa9-22fc-463b-82f5-a670b92ec699)

Also to note, clicking on the link for "ACCOMMODATION TYPE END DATE" leads to a strange page:

![image](https://github.com/user-attachments/assets/472f5669-a437-4884-a901-5c8dd4418b3c)

Finally, there does not seem to be an attribute called "ACCOMMODATION TYPE END DATE" in Mauro:

![image](https://github.com/user-attachments/assets/7352cb58-35c4-4773-8b83-9c32301e9d09)

# Tasks

- [x] Investigate why these pages render the way they do
- [ ] Check that the ingest files had the expected content to replicate these pages
- [x] If the ingest files are correct, look into why the ingest may have imported data/content this way

# Related

- NHSDigital/DataDictionaryPublication#506

**Comment by pjmonks** [comment]
I've commented on:

- NHSDigital/DataDictionaryPublication#506

Since there are issues with semantic links, as I've described in NHSDigital/DataDictionaryPublication#523, I think these are related. I've stated this bug is out of scope for System C to fix and must be handled by the Mauro team (@jamesrwelch).

Closing this issue as "Cannot fix".
